const PATH='./Data/files.json',DEF={xMin:20,xMax:20000,yMin:60,yMax:120};let items=[],cache=new Map(),chart;
const $=s=>document.querySelector(s),list=$('#list'),status=$('#status'),tbody=$('#tbody');
function msg(t,e=false){status.textContent=t;status.classList.toggle('error',e)}
async function manifest(){msg('Data/files.json에서 목록을 불러오는 중입니다.');try{let r=await fetch(PATH+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);let j=await r.json();items=j.files.map((v,i)=>({id:'d'+i,file:typeof v==='string'?v:v.file,name:typeof v==='string'?v:(v.name||v.file),cal:typeof v==='string'?0:Number(v.calibration||0),sel:typeof v==='string'?false:!!v.selected,apply:typeof v==='string'?false:!!v.applyCalibration})).filter(v=>v.file);cards();msg(items.length+'개 파일을 찾았습니다.');await Promise.all(items.filter(v=>v.sel).map(load));draw()}catch(e){console.error(e);msg('Data/files.json을 불러오지 못했습니다.',true)}}
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function cards(){list.innerHTML=items.map(v=>`<article class="card" data-id="${v.id}"><div class="title"><input class="pick" type="checkbox" ${v.sel?'checked':''}><div><div class="name">${esc(v.name)}</div><div class="path">Data/${esc(v.file)}</div></div></div><div class="cal"><label>보정값(dB)</label><input class="value" type="number" step="0.1" value="${v.cal}"><label><input class="apply" type="checkbox" ${v.apply?'checked':''}> 적용</label></div></article>`).join('');
list.querySelectorAll('.card').forEach(c=>{let v=items.find(x=>x.id===c.dataset.id),p=c.querySelector('.pick'),n=c.querySelector('.value'),a=c.querySelector('.apply');p.onchange=async()=>{v.sel=p.checked;if(v.sel)await load(v);draw()};n.oninput=()=>{v.cal=Number(n.value||0);if(v.sel&&v.apply)draw()};a.onchange=()=>{v.apply=a.checked;if(v.sel)draw()}})}
async function load(v){if(cache.has(v.file))return cache.get(v.file);try{let r=await fetch('./Data/'+encodeURI(v.file)+'?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);let p=Papa.parse(await r.text(),{header:true,dynamicTyping:true,skipEmptyLines:true}),rows=norm(p.data);cache.set(v.file,rows);return rows}catch(e){console.error(e);v.sel=false;let q=$('#'+v.id);msg(v.file+' 파일을 읽지 못했습니다.',true);return[]}}
function norm(rows){if(!rows.length)return[];let k=Object.keys(rows[0]),fk=k.find(x=>['frequency','freq','hz','주파수'].includes(x.trim().toLowerCase()))||k[0],dk=k.find(x=>['db','spl','level','magnitude','값'].includes(x.trim().toLowerCase()))||k[1];return rows.map(r=>({x:Number(r[fk]),y:Number(r[dk])})).filter(p=>p.x>0&&Number.isFinite(p.x)&&Number.isFinite(p.y)).sort((a,b)=>a.x-b.x)}
function axis(){return{xMin:num('#xMin',20,true),xMax:num('#xMax',20000,true),yMin:num('#yMin',60),yMax:num('#yMax',120)}}
function num(s,d,pos=false){let n=Number($(s).value);return Number.isFinite(n)&&(!pos||n>0)?n:d}
function color(n){return getComputedStyle(document.body).getPropertyValue(n).trim()}
function tick(v){return({20:'20',50:'50',100:'100',200:'200',500:'500',1000:'1k',2000:'2k',5000:'5k',10000:'10k',20000:'20k'})[v]||''}
function ff(v){return v>=1000?(v/1000).toFixed(v%1000?1:0)+'k':String(v)}
function signed(v){return(v>=0?'+':'')+Number(v).toFixed(1)}
function draw(){let a=axis(),chosen=items.filter(v=>v.sel),sets=chosen.map(v=>{let c=v.apply?v.cal:0,p=(cache.get(v.file)||[]).filter(x=>x.x>=a.xMin&&x.x<=a.xMax).map(x=>({x:x.x,y:x.y+c}));return{label:v.name+(v.apply?' ('+signed(c)+' dB)':''),data:p,parsing:false,borderWidth:2,pointRadius:p.length>150?0:1.5,tension:0}});
chart?.destroy();chart=new Chart($('#chart'),{type:'line',data:{datasets:sets},options:{responsive:true,maintainAspectRatio:false,animation:false,interaction:{mode:'nearest',intersect:false},scales:{x:{type:'logarithmic',min:a.xMin,max:a.xMax,title:{display:true,text:'Frequency (Hz)',color:color('--text')},ticks:{color:color('--text'),callback:v=>tick(Number(v))},grid:{color:color('--border')}},y:{min:a.yMin,max:a.yMax,title:{display:true,text:'Level (dB)',color:color('--text')},ticks:{color:color('--text'),stepSize:5},grid:{color:color('--border')}}},plugins:{legend:{labels:{color:color('--text'),usePointStyle:true}},tooltip:{callbacks:{title:i=>ff(i[0].parsed.x)+' Hz',label:c=>c.dataset.label+': '+c.parsed.y.toFixed(2)+' dB'}},zoom:{limits:{x:{min:a.xMin,max:a.xMax},y:{min:a.yMin,max:a.yMax}},pan:{enabled:true,mode:'x'},zoom:{wheel:{enabled:true},pinch:{enabled:true},mode:'x'}}}}});
$('#selected').textContent=chosen.length;$('#visible').textContent=sets.filter(s=>s.data.length).length;$('#freqRange').textContent=ff(a.xMin)+'–'+ff(a.xMax)+' Hz';$('#dbRange').textContent=a.yMin+'–'+a.yMax+' dB';
tbody.innerHTML=chosen.map(v=>{let r=cache.get(v.file)||[];return`<tr><td>${esc(v.name)}</td><td>${r.length.toLocaleString()}</td><td>${signed(v.cal)} dB</td><td>${v.apply?'적용':'미적용'}</td><td>${r.length?ff(r[0].x)+'–'+ff(r.at(-1).x)+' Hz':'-'}</td></tr>`}).join('')}
$('#reload').onclick=manifest;$('#all').onclick=async()=>{items.forEach(v=>v.sel=true);document.querySelectorAll('.pick').forEach(x=>x.checked=true);await Promise.all(items.map(load));draw()};$('#none').onclick=()=>{items.forEach(v=>v.sel=false);document.querySelectorAll('.pick').forEach(x=>x.checked=false);draw()};$('#draw').onclick=draw;
$('#axisReset').onclick=()=>{Object.entries(DEF).forEach(([k,v])=>$('#'+k).value=v);draw()};$('#zoomReset').onclick=()=>chart?.resetZoom();$('#save').onclick=()=>{let a=document.createElement('a');a.download='frequency-response.png';a.href=chart.toBase64Image();a.click()};
$('#theme').onclick=e=>{document.body.classList.toggle('dark');e.target.textContent=document.body.classList.contains('dark')?'라이트 모드':'다크 모드';draw()};manifest();